// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO
    tasks (
        id,
        title,
        description,
        status,
        priority,
        assigned_to,
        created_by,
        created_at,
        updated_at,
        start_date,
        due_date
    )
VALUES
    (
        gen_random_uuid(),
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        NOW(),
        NOW(),
        $7,
        $8
    ) RETURNING id, title, description, status, priority, assigned_to, created_by, created_at, updated_at, start_date, due_date
`

type CreateTaskParams struct {
	Title       string
	Description string
	Status      ProgessStatus
	Priority    PriorityStatus
	AssignedTo  uuid.UUID
	CreatedBy   uuid.UUID
	StartDate   pgtype.Timestamp
	DueDate     pgtype.Timestamp
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
		arg.CreatedBy,
		arg.StartDate,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.DueDate,
	)
	return i, err
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT tasks.id, tasks.title, tasks.description, tasks.status, tasks.priority, tasks.assigned_to, tasks.created_by, tasks.created_at, tasks.updated_at, tasks.start_date, tasks.due_date , users.name FROM tasks  JOIN users ON tasks.assigned_to = users.id
`

type GetAllTasksRow struct {
	ID          uuid.UUID
	Title       string
	Description string
	Status      ProgessStatus
	Priority    PriorityStatus
	AssignedTo  uuid.UUID
	CreatedBy   uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	StartDate   pgtype.Timestamp
	DueDate     pgtype.Timestamp
	Name        string
}

func (q *Queries) GetAllTasks(ctx context.Context) ([]GetAllTasksRow, error) {
	rows, err := q.db.Query(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTasksRow
	for rows.Next() {
		var i GetAllTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.DueDate,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
